
#include <iostream> 
#include <map>

int main(int argc, char ** argv) 
{

	std::string str;
	const char space = ' ';

	std::map<unsigned char, std::string> index = {std::pair<unsigned char, std::string>({1, "+"}),
                                                    std::pair<unsigned char, std::string>({2, "++"}),
                                                    std::pair<unsigned char, std::string>({3, "+++"}),
                                                    std::pair<unsigned char, std::string>({4, "++++"}),
                                                    std::pair<unsigned char, std::string>({5, "+++++"}),
                                                    std::pair<unsigned char, std::string>({6, "++++++"}),
                                                    std::pair<unsigned char, std::string>({7, "+++++++"}),
                                                    std::pair<unsigned char, std::string>({8, "++++++++"}),
                                                    std::pair<unsigned char, std::string>({9, "+++++++++"}),
                                                    std::pair<unsigned char, std::string>({10, "++++++++++"}),
                                                    std::pair<unsigned char, std::string>({11, "+++++++++++"}),
                                                    std::pair<unsigned char, std::string>({12, "++++++++++++"}),
                                                    std::pair<unsigned char, std::string>({13, "+++++++++++++"}),
                                                    std::pair<unsigned char, std::string>({14, "++++++++++++++"}),
                                                    std::pair<unsigned char, std::string>({15, "+++[>+++++<-]>"}),
                                                    std::pair<unsigned char, std::string>({16, ">+[>-[-<]>>]>"}),
                                                    std::pair<unsigned char, std::string>({17, ">+[>-[-<]>>]>+"}),
                                                    std::pair<unsigned char, std::string>({18, "+++[>++++++<-]>"}),
                                                    std::pair<unsigned char, std::string>({19, "+++[>++++++<-]>+"}),
                                                    std::pair<unsigned char, std::string>({20, "++++[>+++++<-]>"}),
                                                    std::pair<unsigned char, std::string>({21, "-[+[-<]>>++++]<"}),
                                                    std::pair<unsigned char, std::string>({22, ">++[++[<]>->+]<"}),
                                                    std::pair<unsigned char, std::string>({23, ">-[++++[<]>->+]<"}),
                                                    std::pair<unsigned char, std::string>({24, "++++[>++++++<-]>"}),
                                                    std::pair<unsigned char, std::string>({25, "+++++[>+++++<-]>"}),
                                                    std::pair<unsigned char, std::string>({26, ">++[[+<]>+>++]<-"}),
                                                    std::pair<unsigned char, std::string>({27, ">+[--[>+<<]>-]>-"}),
                                                    std::pair<unsigned char, std::string>({28, ">+[--[>+<<]>-]>"}),
                                                    std::pair<unsigned char, std::string>({29, ">+[--[<]>>+<-]>"}),
                                                    std::pair<unsigned char, std::string>({30, ">+[--[<]>>+<-]>+"}),
                                                    std::pair<unsigned char, std::string>({31, ">+[--[<]>>+<-]>++"}),
                                                    std::pair<unsigned char, std::string>({32, ">+[-->---[-<]>]>"}),
                                                    std::pair<unsigned char, std::string>({33, ">+[-->---[-<]>]>+"}),
                                                    std::pair<unsigned char, std::string>({34, "--[>--<+++++++]>--"}),
                                                    std::pair<unsigned char, std::string>({35, "--[>--<+++++++]>-"}),
                                                    std::pair<unsigned char, std::string>({36, "--[>--<+++++++]>"}),
                                                    std::pair<unsigned char, std::string>({37, "---[>+<+++++++]>"}),
                                                    std::pair<unsigned char, std::string>({38, "---[>+<+++++++]>+"}),
                                                    std::pair<unsigned char, std::string>({39, "---[>+<+++++++]>++"}),
                                                    std::pair<unsigned char, std::string>({40, "--[>+<++++++]>---"}),
                                                    std::pair<unsigned char, std::string>({41, "--[>+<++++++]>--"}),
                                                    std::pair<unsigned char, std::string>({42, "--[>+<++++++]>-"}),
                                                    std::pair<unsigned char, std::string>({43, "--[>+<++++++]>"}),
                                                    std::pair<unsigned char, std::string>({44, "--[>+<++++++]>+"}),
                                                    std::pair<unsigned char, std::string>({45, "--[>+<++++++]>++"}),
                                                    std::pair<unsigned char, std::string>({46, "--[>+<++++++]>+++"}),
                                                    std::pair<unsigned char, std::string>({47, "-[>+<-----]>----"}),
                                                    std::pair<unsigned char, std::string>({48, "-[>+<-----]>---"}),
                                                    std::pair<unsigned char, std::string>({49, "-[>+<-----]>--"}),
                                                    std::pair<unsigned char, std::string>({50, "-[>+<-----]>-"}),
                                                    std::pair<unsigned char, std::string>({51, "-[>+<-----]>"}),
                                                    std::pair<unsigned char, std::string>({52, "-[>+<-----]>+"}),
                                                    std::pair<unsigned char, std::string>({53, "-[>+<-----]>++"}),
                                                    std::pair<unsigned char, std::string>({54, "-[>+<-----]>+++"}),
                                                    std::pair<unsigned char, std::string>({55, "-[>+<-----]>++++"}),
                                                    std::pair<unsigned char, std::string>({56, "-[>+<-----]>+++++"}),
                                                    std::pair<unsigned char, std::string>({57, "-[>+<+++++++++]>"}),
                                                    std::pair<unsigned char, std::string>({58, "-[>+<+++++++++]>+"}),
                                                    std::pair<unsigned char, std::string>({59, "----[>+<----]>----"}),
                                                    std::pair<unsigned char, std::string>({60, "----[>+<----]>---"}),
                                                    std::pair<unsigned char, std::string>({61, "----[>+<----]>--"}),
                                                    std::pair<unsigned char, std::string>({62, "----[>+<----]>-"}),
                                                    std::pair<unsigned char, std::string>({63, "----[>+<----]>"}),
                                                    std::pair<unsigned char, std::string>({64, "----[>+<----]>+"}),
                                                    std::pair<unsigned char, std::string>({65, "----[>+<----]>++"}),
                                                    std::pair<unsigned char, std::string>({66, "----[>+<----]>+++"}),
                                                    std::pair<unsigned char, std::string>({67, "----[>---<----]>"}),
                                                    std::pair<unsigned char, std::string>({68, "----[>---<----]>+"}),
                                                    std::pair<unsigned char, std::string>({69, "----[>---<----]>++"}),
                                                    std::pair<unsigned char, std::string>({70, "-[>+<-------]>---"}),
                                                    std::pair<unsigned char, std::string>({71, "-[>+<-------]>--"}),
                                                    std::pair<unsigned char, std::string>({72, "-[>+<-------]>-"}),
                                                    std::pair<unsigned char, std::string>({73, "-[>+<-------]>"}),
                                                    std::pair<unsigned char, std::string>({74, "-[>+<-------]>+"}),
                                                    std::pair<unsigned char, std::string>({75, "-[>+<-------]>++"}),
                                                    std::pair<unsigned char, std::string>({76, "-[>+<-------]>+++"}),
                                                    std::pair<unsigned char, std::string>({77, "-[>+<---]>--------"}),
                                                    std::pair<unsigned char, std::string>({78, "-[>+<---]>-------"}),
                                                    std::pair<unsigned char, std::string>({79, "-[>+<---]>------"}),
                                                    std::pair<unsigned char, std::string>({80, "-[>+<---]>-----"}),
                                                    std::pair<unsigned char, std::string>({81, "-[>+<---]>----"}),
                                                    std::pair<unsigned char, std::string>({82, "-[>+<---]>---"}),
                                                    std::pair<unsigned char, std::string>({83, "-[>+<---]>--"}),
                                                    std::pair<unsigned char, std::string>({84, "-[>+<---]>-"}),
                                                    std::pair<unsigned char, std::string>({85, "-[>+<---]>"}),
                                                    std::pair<unsigned char, std::string>({86, "-[>+<---]>+"}),
                                                    std::pair<unsigned char, std::string>({87, "-[>+<---]>++"}),
                                                    std::pair<unsigned char, std::string>({88, "-[>+<---]>+++"}),
                                                    std::pair<unsigned char, std::string>({89, "-[>+<---]>++++"}),
                                                    std::pair<unsigned char, std::string>({90, "-[>+<---]>+++++"}),
                                                    std::pair<unsigned char, std::string>({91, "-[>+<---]>++++++"}),
                                                    std::pair<unsigned char, std::string>({92, "-[>+<---]>+++++++"}),
                                                    std::pair<unsigned char, std::string>({93, "-[>+<---]>++++++++"}),
                                                    std::pair<unsigned char, std::string>({94, "-[>+<---]>+++++++++"}),
                                                    std::pair<unsigned char, std::string>({95, "-[>++<-----]>-------"}),
                                                    std::pair<unsigned char, std::string>({96, "-[>++<-----]>------"}),
                                                    std::pair<unsigned char, std::string>({97, "-[>++<-----]>-----"}),
                                                    std::pair<unsigned char, std::string>({98, "-[>++<-----]>----"}),
                                                    std::pair<unsigned char, std::string>({99, "-[>++<-----]>---"}),
                                                    std::pair<unsigned char, std::string>({100, "-[>++<-----]>--"}),
                                                    std::pair<unsigned char, std::string>({101, "-[>++<-----]>-"}),
                                                    std::pair<unsigned char, std::string>({102, "-[>++<-----]>"}),
                                                    std::pair<unsigned char, std::string>({103, "-[>++<-----]>+"}),
                                                    std::pair<unsigned char, std::string>({104, "-[>++<-----]>++"}),
                                                    std::pair<unsigned char, std::string>({105, "-[>++<-----]>+++"}),
                                                    std::pair<unsigned char, std::string>({106, "-[>++<-----]>++++"}),
                                                    std::pair<unsigned char, std::string>({107, "-[>++<-----]>+++++"}),
                                                    std::pair<unsigned char, std::string>({108, "-[>--<-------]>--"}),
                                                    std::pair<unsigned char, std::string>({109, "-[>--<-------]>-"}),
                                                    std::pair<unsigned char, std::string>({110, "-[>--<-------]>"}),
                                                    std::pair<unsigned char, std::string>({111, "-[>--<-------]>+"}),
                                                    std::pair<unsigned char, std::string>({112, "-[>--<-------]>++"}),
                                                    std::pair<unsigned char, std::string>({113, "-[>++<+++++++++]>-"}),
                                                    std::pair<unsigned char, std::string>({114, "-[>++<+++++++++]>"}),
                                                    std::pair<unsigned char, std::string>({115, "-[>++<+++++++++]>+"}),
                                                    std::pair<unsigned char, std::string>({116, "--------[>+++<--]>"}),
                                                    std::pair<unsigned char, std::string>({117, "----[>+++++<--]>-"}),
                                                    std::pair<unsigned char, std::string>({118, "----[>+++++<--]>"}),
                                                    std::pair<unsigned char, std::string>({119, "------[>+++<--]>"}),
                                                    std::pair<unsigned char, std::string>({120, "----[>+++<--]>--"}),
                                                    std::pair<unsigned char, std::string>({121, "----[>+++<--]>-"}),
                                                    std::pair<unsigned char, std::string>({122, "----[>+++<--]>"}),
                                                    std::pair<unsigned char, std::string>({123, "--[>+<--]>----"}),
                                                    std::pair<unsigned char, std::string>({124, "--[>+<--]>---"}),
                                                    std::pair<unsigned char, std::string>({125, "--[>+<--]>--"}),
                                                    std::pair<unsigned char, std::string>({126, "--[>+<--]>-"}),
                                                    std::pair<unsigned char, std::string>({127, "--[>+<--]>"}),
                                                    std::pair<unsigned char, std::string>({128, "--[>-<--]>-"}),
                                                    std::pair<unsigned char, std::string>({129, "--[>-<--]>"}),
                                                    std::pair<unsigned char, std::string>({130, "--[>-<--]>+"}),
                                                    std::pair<unsigned char, std::string>({131, "--[>-<--]>++"}),
                                                    std::pair<unsigned char, std::string>({132, "--[>-<--]>+++"}),
                                                    std::pair<unsigned char, std::string>({133, "--[>-<--]>++++"}),
                                                    std::pair<unsigned char, std::string>({134, "----[>---<--]>"}),
                                                    std::pair<unsigned char, std::string>({135, "----[>---<--]>+"}),
                                                    std::pair<unsigned char, std::string>({136, "----[>---<--]>++"}),
                                                    std::pair<unsigned char, std::string>({137, "------[>---<--]>"}),
                                                    std::pair<unsigned char, std::string>({138, "----[>-----<--]>"}),
                                                    std::pair<unsigned char, std::string>({139, "----[>-----<--]>+"}),
                                                    std::pair<unsigned char, std::string>({140, "--------[>---<--]>"}),
                                                    std::pair<unsigned char, std::string>({141, "-[>--<+++++++++]>-"}),
                                                    std::pair<unsigned char, std::string>({142, "-[>--<+++++++++]>"}),
                                                    std::pair<unsigned char, std::string>({143, "-[>--<+++++++++]>+"}),
                                                    std::pair<unsigned char, std::string>({144, "-[>++<-------]>--"}),
                                                    std::pair<unsigned char, std::string>({145, "-[>++<-------]>-"}),
                                                    std::pair<unsigned char, std::string>({146, "-[>++<-------]>"}),
                                                    std::pair<unsigned char, std::string>({147, "-[>++<-------]>+"}),
                                                    std::pair<unsigned char, std::string>({148, ">-[--[-->]<<-]>-"}),
                                                    std::pair<unsigned char, std::string>({149, ">-[--[-->]<<-]>"}),
                                                    std::pair<unsigned char, std::string>({150, "-[+>+[<]>++]>-"}),
                                                    std::pair<unsigned char, std::string>({151, "-[+>+[<]>++]>"}),
                                                    std::pair<unsigned char, std::string>({152, "-[+>+[<]>++]>+"}),
                                                    std::pair<unsigned char, std::string>({153, "-[>--<-----]>-"}),
                                                    std::pair<unsigned char, std::string>({154, "-[>--<-----]>"}),
                                                    std::pair<unsigned char, std::string>({155, "-[>--<-----]>+"}),
                                                    std::pair<unsigned char, std::string>({156, "-[>--<-----]>++"}),
                                                    std::pair<unsigned char, std::string>({157, ">+[++[<]>->+]<"}),
                                                    std::pair<unsigned char, std::string>({158, "-[+[+++<]>>+]<"}),
                                                    std::pair<unsigned char, std::string>({159, "-[+[+++<]>>+]<+"}),
                                                    std::pair<unsigned char, std::string>({160, ">-[-[>-<-<]>]>"}),
                                                    std::pair<unsigned char, std::string>({161, ">-[-[>-<-<]>]>+"}),
                                                    std::pair<unsigned char, std::string>({162, ">++>-[-[-<]>>-]<"}),
                                                    std::pair<unsigned char, std::string>({163, "+[->-[<]>----]>"}),
                                                    std::pair<unsigned char, std::string>({164, "-[+>+++[+<]>+]>"}),
                                                    std::pair<unsigned char, std::string>({165, "+[-[-<]>>-]<---"}),
                                                    std::pair<unsigned char, std::string>({166, "+[-[-<]>>-]<--"}),
                                                    std::pair<unsigned char, std::string>({167, "+[-[-<]>>-]<-"}),
                                                    std::pair<unsigned char, std::string>({168, "+[-[-<]>>-]<"}),
                                                    std::pair<unsigned char, std::string>({169, "-[>-<---]>--"}),
                                                    std::pair<unsigned char, std::string>({170, "-[>-<---]>-"}),
                                                    std::pair<unsigned char, std::string>({171, "-[>-<---]>"}),
                                                    std::pair<unsigned char, std::string>({172, "-[>-<---]>+"}),
                                                    std::pair<unsigned char, std::string>({173, "-[>-<---]>++"}),
                                                    std::pair<unsigned char, std::string>({174, "-[>-<---]>+++"}),
                                                    std::pair<unsigned char, std::string>({175, "-[>-<---]>++++"}),
                                                    std::pair<unsigned char, std::string>({176, "+[->--[--<]>]>"}),
                                                    std::pair<unsigned char, std::string>({177, "+[->--[--<]>]>+"}),
                                                    std::pair<unsigned char, std::string>({178, "-[-[>>-<-<+]>]>"}),
                                                    std::pair<unsigned char, std::string>({179, ">---[[+<]>>++]<"}),
                                                    std::pair<unsigned char, std::string>({180, ">-[-<[+<]>>--]<"}),
                                                    std::pair<unsigned char, std::string>({181, "-[>-<-------]>--"}),
                                                    std::pair<unsigned char, std::string>({182, "-[>-<-------]>-"}),
                                                    std::pair<unsigned char, std::string>({183, "-[>-<-------]>"}),
                                                    std::pair<unsigned char, std::string>({184, "-[>-<-------]>+"}),
                                                    std::pair<unsigned char, std::string>({185, "-[>-<-------]>++"}),
                                                    std::pair<unsigned char, std::string>({186, "+[-[>+++<<]>-]>"}),
                                                    std::pair<unsigned char, std::string>({187, "-[+>+[++<]>+]>--"}),
                                                    std::pair<unsigned char, std::string>({188, "-[+>+[++<]>+]>-"}),
                                                    std::pair<unsigned char, std::string>({189, "-[+>+[++<]>+]>"}),
                                                    std::pair<unsigned char, std::string>({190, "++[-->-[<]>-]>"}),
                                                    std::pair<unsigned char, std::string>({191, ">-[-[<]>>-<-]>"}),
                                                    std::pair<unsigned char, std::string>({192, "+[-[>-<<]>-]>"}),
                                                    std::pair<unsigned char, std::string>({193, "-[+[>-<<]>+]>"}),
                                                    std::pair<unsigned char, std::string>({194, "-[+[>-<<]>+]>+"}),
                                                    std::pair<unsigned char, std::string>({195, "-[+[>-<<]>+]>++"}),
                                                    std::pair<unsigned char, std::string>({196, "+[->-[---<]>+]>"}),
                                                    std::pair<unsigned char, std::string>({197, ">-[-[<]>+>--]<"}),
                                                    std::pair<unsigned char, std::string>({198, ">+[--[-<]>>-<]>"}),
                                                    std::pair<unsigned char, std::string>({199, ">+[-->-[-<]>]>-"}),
                                                    std::pair<unsigned char, std::string>({200, ">+[-->-[-<]>]>"}),
                                                    std::pair<unsigned char, std::string>({201, ">+[-->-[-<]>]>+"}),
                                                    std::pair<unsigned char, std::string>({202, "-[>-<-----]>---"}),
                                                    std::pair<unsigned char, std::string>({203, "-[>-<-----]>--"}),
                                                    std::pair<unsigned char, std::string>({204, "-[>-<-----]>-"}),
                                                    std::pair<unsigned char, std::string>({205, "-[>-<-----]>"}),
                                                    std::pair<unsigned char, std::string>({206, "-[>-<-----]>+"}),
                                                    std::pair<unsigned char, std::string>({207, "-[>-<-----]>++"}),
                                                    std::pair<unsigned char, std::string>({208, "-[>-<-----]>+++"}),
                                                    std::pair<unsigned char, std::string>({209, "-[+[++<]>>++]<"}),
                                                    std::pair<unsigned char, std::string>({210, "+[->-[-<]>-]>"}),
                                                    std::pair<unsigned char, std::string>({211, "+[->-[-<]>-]>+"}),
                                                    std::pair<unsigned char, std::string>({212, "--[>-<++++++]>-"}),
                                                    std::pair<unsigned char, std::string>({213, "--[>-<++++++]>"}),
                                                    std::pair<unsigned char, std::string>({214, "--[>-<++++++]>+"}),
                                                    std::pair<unsigned char, std::string>({215, "--[>-<++++++]>++"}),
                                                    std::pair<unsigned char, std::string>({216, ">-[++>-[<]>+]>-"}),
                                                    std::pair<unsigned char, std::string>({217, ">-[++>-[<]>+]>"}),
                                                    std::pair<unsigned char, std::string>({218, ">-[++>-[<]>+]>+"}),
                                                    std::pair<unsigned char, std::string>({219, ">+[-<[+<]>>--]<"}),
                                                    std::pair<unsigned char, std::string>({220, "-[+>+[+++<]>+]>"}),
                                                    std::pair<unsigned char, std::string>({221, ">+[-->-[<]>-]>"}),
                                                    std::pair<unsigned char, std::string>({222, ">+[+[+<]>>-<]>-"}),
                                                    std::pair<unsigned char, std::string>({223, ">+[+[+<]>>-<]>"}),
                                                    std::pair<unsigned char, std::string>({224, ">+[+[+<]>>-<]>+"}),
                                                    std::pair<unsigned char, std::string>({225, ">-[[+<]>>+>++]<"}),
                                                    std::pair<unsigned char, std::string>({226, ">-[++[<]>>-<+]>-"}),
                                                    std::pair<unsigned char, std::string>({227, ">-[++[<]>>-<+]>"}),
                                                    std::pair<unsigned char, std::string>({228, ">-[++[>-<<]>+]>"}),
                                                    std::pair<unsigned char, std::string>({229, ">--[[-<]>->--]<"}),
                                                    std::pair<unsigned char, std::string>({230, ">--[[-<]>->--]<+"}),
                                                    std::pair<unsigned char, std::string>({231, "-----[>-----<+]>"}),
                                                    std::pair<unsigned char, std::string>({232, "----[>------<+]>"}),
                                                    std::pair<unsigned char, std::string>({233, ">+[----[<]>+>-]<"}),
                                                    std::pair<unsigned char, std::string>({234, ">--[--[<]>+>-]<"}),
                                                    std::pair<unsigned char, std::string>({235, "+[-[+<]>>----]<"}),
                                                    std::pair<unsigned char, std::string>({236, "----[>-----<+]>"}),
                                                    std::pair<unsigned char, std::string>({237, "---[>------<+]>-"}),
                                                    std::pair<unsigned char, std::string>({238, "---[>------<+]>"}),
                                                    std::pair<unsigned char, std::string>({239, ">-[>+[+<]>>]>-"}),
                                                    std::pair<unsigned char, std::string>({240, ">-[>+[+<]>>]>"}),
                                                    std::pair<unsigned char, std::string>({241, "---------------"}),
                                                    std::pair<unsigned char, std::string>({242, "--------------"}),
                                                    std::pair<unsigned char, std::string>({243, "-------------"}),
                                                    std::pair<unsigned char, std::string>({244, "------------"}),
                                                    std::pair<unsigned char, std::string>({245, "-----------"}),
                                                    std::pair<unsigned char, std::string>({246, "----------"}),
                                                    std::pair<unsigned char, std::string>({247, "---------"}),
                                                    std::pair<unsigned char, std::string>({248, "--------"}),
                                                    std::pair<unsigned char, std::string>({249, "-------"}),
                                                    std::pair<unsigned char, std::string>({250, "------"}),
                                                    std::pair<unsigned char, std::string>({251, "-----"}),
                                                    std::pair<unsigned char, std::string>({252, "----"}),
                                                    std::pair<unsigned char, std::string>({253, "---"}),
                                                    std::pair<unsigned char, std::string>({254, "--"}),
                                                    std::pair<unsigned char, std::string>({255, "-"})};

	if (argc <= 1) {

		std::cout << "Type a string to be converted into brainfuck" << std::endl;

        return 0;

	} else {

		int c{};

		for (c = 1; c < argc; c++) {

			if (c != argc -1) {

				str += std::string(argv[c]) + space;

			} else {

				str += std::string(argv[c]);

			}

		}

	}

	std::string bfstr;

    for (char ch : str) {

        unsigned char val = (unsigned char)(ch);

        std::string bfs = index[val];

        bfstr += bfs + ".>"; 

    }


    bfstr.pop_back();

    std::cout << bfstr;


	return 0;

}